### ISSUE TITLE
The build folder is too large

### ISSUE THREAD

**Issue by callmeYe** [lxieyang/chrome-extension-boilerplate-react#10]
I developed with jQuery, and the code was about 270 KB in size. But using this scaffold, I found that the packed build folder was 7MB, it's too large.

**Comment by lxieyang** [comment]
Yeah, I think you can probably create a production webpack configuration that gets rid of the sourcemap stuff that are really large. I'll also see if I can do that in the next release!
Thanks for spotting this!
