### ISSUE TITLE
popup.jsx not hot reloading properly when adding a chrome runtime listener

### ISSUE THREAD

**Issue by datgrog** [lxieyang/chrome-extension-boilerplate-react#100]
The change here is that my content script talk to my popup 1 sec after a page load using `chrome.runtime.sendMessage` and my popup to received it using `chrome.runtime.onMessage.addListener`. See for yourself here: https://github.com/datgrog/chrome-extension-boilerplate-react

- When you run `npm start`, go to [https://example.com/](https://example.com/) and open the dev tool (F12).
You will see that there is ```Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.``` which is normal as no popup is open.
- Then open the popup or open a new tab with your `extension_id` chrome-extension:// `extension_id` /popup.html and reload the example.com page, you will see that it works as expected.
- Then edit the `Popup.jsx` with anything, a log, or modify the text of the component. The popup reloads and reflects the change. **Then** reload the example.com page, you will see that the message does not pass anymore.

To make it work again I need to reload the extension form the extension page which defeat the purpose..

**Comment by lxieyang** [comment]
fixed in the latest version with react 18
