### ISSUE TITLE
Cant save data to localstorage

### ISSUE THREAD

**Issue by hungdev** [lxieyang/chrome-extension-boilerplate-react#104]
thank for your template, @lxieyang 
In Popup.jsx i used:
```
      chrome.storage.local.set({ 'value': 'theValue' }, function () {
        // Notify that we saved.
        console.log('Settings saved'); 
      });
```
I can see the log 'Settings saved' show up,
      but when i inspect and open Application tab, i dont see value that i inserted here? what's wrong with me?
      
![image](https://user-images.githubusercontent.com/12009276/158515752-d5cd861c-b281-4b0d-9d2b-3a7ca6e0c6f6.png)
Thank you

**Comment by hungdev** [comment]
i misunderstand about chrome.storage and localStorage

**Comment by cancan101** [comment]
What was the conclusion / fix here?

**Comment by hungdev** [comment]
@cancan101 
chrome.storage will save data in extension storage, and localStorage will save in chrome => application tab
so im using `chrome.storage.local.set`, it cant save in application tab. If you want to save to application tab of chrome, you need to use localStorage.setItem
