### ISSUE TITLE
Using Sass instead of sass-node in package.json

### ISSUE THREAD

**Issue by elton-lau** [lxieyang/chrome-extension-boilerplate-react#105]
**Problem**
Library sass-node is now depreciated (https://sass-lang.com/blog/libsass-is-deprecated) and it contains pre-requisites (e.g. Python, Visual Code) that sometimes the simple npm install cannot be executed well.

**Suggestion**
Remove sass-node and replace with Sass (https://www.npmjs.com/package/sass).

**Comment by amehito** [comment]
deeply agree, sass-node is totally shit

**Comment by shoeferlin** [comment]
Agree!

**Comment by fhefh2015** [comment]
Agree!

sass - npm 
https://www.npmjs.com/package/sass

**Comment by dyingg** [comment]
Agree!

**Comment by joshbickett** [comment]
Yes, I also find issues with this.

**Comment by lxieyang** [comment]
done!
