### ISSUE TITLE
HMR not working - WebSocket connection to 'wss://localhost:3003/ws' failed

### ISSUE THREAD

**Issue by goldylucks** [lxieyang/chrome-extension-boilerplate-react#107]
HMR isn't working for me, and I have to reload the unpacked extension on every change through `chrome://extensions/`

Not sure if it's related to that WS error?

or it's because I'm on an https domain and have webpack running on localhost?

if so, is there a way around this? sounds like the most basic use case for developing an extension, so there must be away w/o jumping through hoops.

if not, I could try:
1. self certifying my localhost
2. expose webpack dev server through local tunnel

would love any insights here and thanks for the great project!!

**Comment by udbmnm** [comment]
> 

Your port 3000 is being used?

**Comment by kbyatnal** [comment]
having the same issue, any luck @goldylucks?

**Comment by goldylucks** [comment]
nope, and I'm not using this project anymore 🤷‍♀️

**Comment by kbyatnal** [comment]
for anyone else that comes along, I switched over to https://github.com/SimplifyJobs/webpack-ext-reloader and it works great
