### ISSUE TITLE
hot reload newly added entry point

### ISSUE THREAD

**Issue by hellofantastic** [lxieyang/chrome-extension-boilerplate-react#11]
Let me say pretty marvellous repo, I've learned a bit about webpack.

I decided to add another  entry point in the webpack.config
```
  indexScript: path.join(__dirname, 'src', 'index.jsx'),
```

inside this file is this:
it makes use of  [InboxSDK.js](https://www.inboxsdk.com/)
it adds functionality to various parts of Gmail web UI and accepts React nicely for UI building
I added it to webpack config and it gets copied over where it needs to be
```
import React from 'react';
import ReactDOM from 'react-dom';

const TestFeature = () => <div>boo hoo</div>; //editing these components does not trigger a reload
const Sidebar = () => <div>Boo hoo hoo</div>;

InboxSDK.load(2, 'app-id').then((sdk) => {

    //Add Compose new window bottom toolbar
    sdk.Compose.registerComposeViewHandler((composeView) => {
        composeView.addButton({
            title: "Test Feature",
            iconUrl: chrome.runtime.getURL('images/template-list-256x256.svg'),
            hasDropdown: true,
            onClick: (event) => {
                ReactDOM.render(<TestFeature />, event.dropdown.el);
            }
        });
    });

    //Sidebar 
    let el = document.createElement('div')
    ReactDOM.render(<Sidebar />, el)

    const panelView = sdk.Global.addSidebarContentPanel({
        title: 'Sidebar test',
        iconUrl: 'sidebarlogo.png',
        el: el
    })

    //Auto Open sidebar
    //Mainly handle for development
    panelView.then(function (panel) {
        panel.open()
    });

});
```

Everything loads up and works except no magic reload for indexScript
When I save indexScript the webserver recompiles build updates but I need to refresh extension page setting and then reload browser 

Any insight much appreciated

**Comment by hellofantastic** [comment]
Okay so reading this [(why?) from readme](https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/issues/4#issuecomment-261788690). 
Sorry for being dense but does this mean you can't get HMR with content scripts?

**Comment by hellofantastic** [comment]
Not exactly but I kept reading and this gets content scripts reloaded,
https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/issues/4#issuecomment-349454698

**Comment by Jaydip-M** [comment]
Can you please share the code for loading a react component to gmail sidebar using inboxSDK ?
I'm trying soo hard but not able to make it work

Thanks :)
