### ISSUE TITLE
React-hot-loader is unused

### ISSUE THREAD

**Issue by headfire94** [lxieyang/chrome-extension-boilerplate-react#114]
Currently whole page re-loads with default webpack hot reload. React hot loader doesn't work because 

To start using react-hot-loader need to follow instruction https://github.com/gaearon/react-hot-loader#getting-started
> Mark your root component as hot-exported:

But it won't work because `eval` not supported in current env

**Comment by Godiswill** [comment]
I also fixed this by react-refresh, here is a [repo](https://github.com/Godiswill/cra-crx-boilerplate).

**Comment by lxieyang** [comment]
fixed in the latest version with react 18
