### ISSUE TITLE
How to import a jsx react in content script

### ISSUE THREAD

**Issue by moshOntong-IT** [lxieyang/chrome-extension-boilerplate-react#119]
So I was planning to create a popover when the user select some text in web content.

Before I manually coded like this
`const popWrapper = document.createElement("div");
    popWrapper.id = "kit-translator-button";
    const popIcon = document.createElement("div");
    popIcon.classList.add("kit-pop-icon");
    popIcon.innerHTML = `<svg version="1.1" id="anna_vital_language_icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px" y="0px" width="15px" height="15px" fill="#ffff" viewBox="0 0 256 256" enable-background="new 0 0 256 256" xml:space="preserve">
  <path d="M62.4,101c-1.5-2.1-2.1-3.4-1.8-3.9c0.2-0.5,1.6-0.7,3.9-0.5c2.3,0.2,4.2,0.5,5.8,0.9c1.5,0.4,2.8,1,3.8,1.7
   c1,0.7,1.8,1.5,2.3,2.6c0.6,1,1,2.3,1.4,3.7c0.7,2.8,0.5,4.7-0.5,5.7c-1.1,1-2.6,0.8-4.6-0.6c-2.1-1.4-3.9-2.8-5.5-4.2
   C65.5,105.1,63.9,103.2,62.4,101z M40.7,190.1c4.8-2.1,9-4.2,12.6-6.4c3.5-2.1,6.6-4.4,9.3-6.8c2.6-2.3,5-4.9,7-7.7
   c2-2.7,3.8-5.8,5.4-9.2c1.3,1.2,2.5,2.4,3.8,3.5c1.2,1.1,2.5,2.2,3.8,3.4c1.3,1.2,2.8,2.4,4.3,3.8c1.5,1.4,3.3,2.8,5.3,4.5
   c0.7,0.5,1.4,0.9,2.1,1c0.7,0.1,1.7,0,3.1-0.6c1.3-0.5,3-1.4,5.1-2.8c2.1-1.3,4.7-3.1,7.9-5.4c1.6-1.1,2.4-2,2.3-2.7
   c-0.1-0.7-1-1-2.7-0.9c-3.1,0.1-5.9,0.1-8.3-0.1c-2.5-0.2-5-0.6-7.4-1.4c-2.4-0.8-4.9-1.9-7.5-3.4c-2.6-1.5-5.6-3.6-9.1-6.2
   c1-3.9,1.8-8,2.4-12.4c0.3-2.5,0.6-4.3,0.8-5.6c0.2-1.2,0.5-2.4,0.9-3.3c0.3-0.8,0.4-1.4,0.5-1.9c0.1-0.5-0.1-1-0.4-1.6
   c-0.4-0.5-1-1.1-1.9-1.7c-0.9-0.6-2.2-1.4-3.9-2.3c2.4-0.9,5.1-1.7,7.9-2.6c2.7-0.9,5.7-1.8,8.8-2.7c3-0.9,4.5-1.9,4.6-3.1
   c0.1-1.2-0.9-2.3-3.2-3.5c-1.5-0.8-2.9-1.1-4.3-0.9c-1.4,0.2-3.2,0.9-5.4,2.2c-0.6,0.4-1.8,0.9-3.4,1.6c-1.7,0.7-3.6,1.5-6,2.5
   c-2.4,1-5,2-7.8,3.1c-2.9,1.1-5.8,2.2-8.7,3.2c-2.9,1.1-5.7,2-8.2,2.8c-2.6,0.8-4.6,1.4-6.1,1.6c-3.8,0.8-5.8,1.6-5.9,2.4
   c0,0.8,1.5,1.6,4.4,2.4c1.2,0.3,2.3,0.6,3.1,0.6c0.8,0.1,1.7,0.1,2.5,0c0.8-0.1,1.6-0.3,2.4-0.5c0.8-0.3,1.7-0.7,2.8-1.1
   c1.6-0.8,3.9-1.7,6.9-2.8c2.9-1,6.6-2.4,11.2-4c0.9,2.7,1.4,6,1.4,9.8c0,3.8-0.4,8.1-1.4,13c-1.3-1.1-2.7-2.3-4.2-3.6
   c-1.5-1.3-2.9-2.6-4.3-3.9c-1.6-1.5-3.2-2.5-4.7-3c-1.6-0.5-3.4-0.5-5.5,0c-3.3,0.9-5,1.9-4.9,3.1c0,1.2,1.3,1.8,3.8,1.9
   c0.9,0.1,1.8,0.3,2.7,0.6c0.9,0.3,1.9,0.9,3.2,1.8c1.3,0.9,2.9,2.2,4.7,3.8c1.8,1.6,4.2,3.7,7,6.3c-1.2,2.9-2.6,5.6-4.1,8
   c-1.5,2.5-3.4,5-5.5,7.3c-2.2,2.4-4.7,4.8-7.7,7.2c-3,2.5-6.6,5.1-10.8,7.8c-4.3,2.8-6.5,4.7-6.5,5.6C35,192.1,37,191.7,40.7,190.1z
    M250.5,81.8v165.3l-111.6-36.4L10.5,253.4V76.1l29.9-10V10.4l81.2,28.7L231.3,2.6v73.1L250.5,81.8z M124.2,50.6L22.3,84.6v152.2
   l101.9-33.9V50.6L124.2,50.6z M219.4,71.9V19L138.1,46L219.4,71.9z M227,201.9L196.5,92L176,85.6l-30.9,90.8l18.9,5.9l5.8-18.7
   l31.9,10l5.7,22.3L227,201.9z M174.8,147.7l22.2,6.9l-10.9-42.9L174.8,147.7z"/>
  </svg>
  `;

    //TODO add css in manifestation to make this readable;

    const popWrapperText = document.createElement("SPAN");
    popWrapperText.innerText = "Kitkat Translate";
    popWrapperText.style.color = "white";
    popWrapper.style.fontSize = "14px";

    popWrapper.appendChild(popIcon);
    popWrapper.appendChild(popWrapperText);

    const top =
      selectBoundingClientRect.top + selectBoundingClientRect.height + 6 + "px";
    const left =
      selectBoundingClientRect.left +
      (selectBoundingClientRect.width / 2 - popWrapper.offsetWidth / 2) +
      "px";

    // console.log(top + " " + left);
    popWrapper.style.position = "absolute";
    popWrapper.style.display = "flex";
    popWrapper.style.justifyContent = "space-around";
    popWrapper.style.alignContent = "center";
    popWrapper.style.background = "black";
    popWrapper.style.width = "150px";
    popWrapper.style.padding = "4px";
    popWrapper.style.top = top;
    popWrapper.style.left = left;
    popWrapper.style.cursor = "pointer";

    this.bodyDOM.appendChild(popWrapper);

    if (popWrapper) {
      popWrapper.addEventListener("click", () => {
        if (selectedText.length > 0) {
          const value = selectionTextRange.toString();
          let selectedElement = document.createElement("SPAN");
          selectedElement.className = "kit-node";

          selectedElement.attachShadow({ mode: "open" });

          // selectedElement.style.backgroundColor = "red";
          // selectedElement.style.fontWeight = "bold";

          let shadowHeader = document.createElement("SPAN");
          shadowHeader.className = "kit-header";

          //TODO optimize css
          let shadowBody = document.createElement("SPAN");
          shadowBody.className = "kit-body";
          shadowBody.style.display = "inline-block";
          shadowBody.style.background = "red";
          shadowBody.innerText = value;

          selectedElement.shadowRoot.appendChild(shadowHeader);
          selectedElement.shadowRoot.appendChild(shadowBody);

          selectionTextRange.deleteContents();
          selectionTextRange.insertNode(selectedElement);

          this.removePopWrapper();
        }
      });
    }
`

As you can see this is not kinda readable thing in our eyes, right. I want to render this element by using the react-dom.

**Comment by DovahBrownies** [comment]
If I'm understanding your correctly, you want to render a custom React component on a webpage of your choice.

You can do so (not tested):

Create your React component:

**MyComponent.js**
```
import React from 'react';

const MyComponent = () => <div>This is my component</div>

export default MyComponent
```

Then in your Content script file, you need to (1) import the component, (2) create or find an element on the webpage to manipulate, and (3) render your React component in that element:

**Content/index.js**
```
// (1) Import component
import MyComponent from '..../MyComponent';

...

// (2) Create `myElement` to manipulate
const myElement = document.createElement('div');
myElement.setAttribute('id', 'MY-COMPONENT-ID');
myElement.setAttribute('style', 'all:unset');

// (2) Find an element in the DOM to manipulate
const foundExistingElement = document.querySelector('SOME-EXISTING-ELEMENT-HERE');

// (2) Here we're injecting `myElement` into the found existing element on the page. (Alternatively we can manipulate the existing element directly - Explained below on (4))
foundExistingElement.prepend(myElement)

// (3) Render your React component inside the `myElement` that you injected into the webpage in step (2).
ReactDOM.render(
  <MyComponent />,
  // (4) Alternatively, you can just target an existing element on the page here without needing to create `myElement`.
  document.getElementById('MY-COMPONENT-ID')
);
```

The above _should_ render `<MyComponent />` on your webpage on every successful load (Given that you target the correct elements).

Now you can add custom events and listeners to make it render on command.

Hope this helps!

**Comment by moshOntong-IT** [comment]
Thank you so much

**Comment by J-Filip** [comment]
I think this should be added in the documentation or added to the content script example code.
