### ISSUE TITLE
goes in an endless loop after i make any code change

### ISSUE THREAD

**Issue by mistersingh179** [lxieyang/chrome-extension-boilerplate-react#158]
any webpage i open after i make a code change starts loading `/contentScript` & `/ws/info` and then reloads the page. this goes in an endless loop

![image](https://user-images.githubusercontent.com/48457746/224414884-da3b3ee7-9a3e-458b-a5d7-c760e1a190e6.png)

**Comment by mistersingh179** [comment]
and then then endless loop only stops when the extension is reloaded.

**Comment by Xe0n** [comment]
Yes, I have the same problem, were you able to solve it?

**Comment by mistersingh179** [comment]
@Xe0n i tried and gave up on this project. switched to vite based project https://github.com/guocaoyi/create-chrome-ext. everything worked there as expected and was a ton faster since it used vite over webpack.
