### ISSUE TITLE
Issue with Content Script Running

### ISSUE THREAD

**Issue by Joetoledano** [lxieyang/chrome-extension-boilerplate-react#169]
Hi! 

I followed the instructions in the Readme and am running the app but am not seeing any of the console.log's from the Content js file in my browser console.

I did not make any changes outside of the names/descriptions. 

Is this supposed to be happening?

**Comment by bramburn** [comment]
check if the hosts are set up correctly in your manifest.

**Comment by sumsalabim** [comment]
Same issue there, there is no way for me to display console logs in the console, tried to add them everywhere

In the Background console tho, this error occurs from time to time: 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/37812273/236802376-230d728b-71c7-4c8c-990a-6c0b29a0a6aa.png">

**Comment by bramburn** [comment]
can you check if the script is being loaded to the page?
Regards,


B.Ramburn BSc (Hons) LLM MCIArb
Snr. Quantity Surveyor & Director at Icelabz

**Comment by Joetoledano** [comment]
@bramburn, this issue is sorted for me - however now running into this issue

` theUncaught Error: SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS`

**Comment by bramburn** [comment]
That's self explanatory. Any code you're loading from 3rd party must be
HTTPS

**Comment by bramburn** [comment]
I've had some plugins where I cannot use the webserver so I have to build
every time

**Comment by Joetoledano** [comment]
Ah cool, will close this then. 

Thanks so for much the help!

**Comment by bramburn** [comment]
No problem!
Regards,


B.Ramburn BSc (Hons) LLM MCIArb
Snr. Quantity Surveyor & Director at Icelabz
