### ISSUE TITLE
Does it supports dev-extension building?

### ISSUE THREAD

**Issue by ShinaZin** [lxieyang/chrome-extension-boilerplate-react#17]
I mean using React.js on `devtools.html` page

**Comment by lxieyang** [comment]
I'm not exactly sure what you meant?

**Comment by GeekaholicLin** [comment]
> I'm not exactly sure what you meant?

Developers can also extend devtools like `vue-devtools` by using Chrome extension API.
https://developer.chrome.com/docs/extensions/mv3/devtools/

**Comment by lxieyang** [comment]
Good to know!

In this case, no, but a good idea for future development!

**Comment by peterhartree** [comment]
If you include `devtools_page` in your extension manifest, the extension will show the following permissions warning on install: 
- Read and change all your data on all websites

I wasted quite some time trying to figure out why I was getting this warning—it's not obvious that the `devtools_page` thing would trigger it.

I've opened a PR suggesting we add a comment about this:
https://github.com/lxieyang/chrome-extension-boilerplate-react/pull/124
