### ISSUE TITLE
Content Scripts SCSS

### ISSUE THREAD

**Issue by dpw1** [lxieyang/chrome-extension-boilerplate-react#18]
Hi there,

I was wondering how can I use SCSS for the **content.styles.css** file?

Thank you!

**Comment by lxieyang** [comment]
Could you try just to start using it? I believe the template will automatically support that, but please let me know if it doesn't work :-)

**Comment by dpw1** [comment]
Hello!

I was unable to make it work via webpack,, so I used the VS Code extension to compile .SCSS to CSS locally, not the most ideal solution but it's doing the job for now.

Anyhow, I'd like to express my thankfulness for your work, I already have two chrome extensions published at the Chrome Store thanks to your boilerplate, also 2 more that I coded for personal use for my work they help me a lot! Thanks for your efforts and kindness.

Kind regards,
Diego

**Comment by lxieyang** [comment]
No problem! I'm so glad to be able to help! Wish you the best luck!
