### ISSUE TITLE
Guidance on upgrading from Samuel's version

### ISSUE THREAD

**Issue by ShravanSunder** [lxieyang/chrome-extension-boilerplate-react#19]
Hi!

do you have any guidance on upgrading from Samuel's older version of the boiler plate?  i'm running webpack 4\react17\etc for for a fairly big personal project.  

thanks,
Shravan

**Comment by lxieyang** [comment]
Maybe check my commit logs at around Oct 26 - 27? I haven't looked at Samuel's code for quite a while now. There are some stuff you need to do when upgrading from webpack 4 to 5, which should be captured in my commit logs.

**Comment by ShravanSunder** [comment]
thanks will do, if i find a procedure that works i will report back
