### ISSUE TITLE
[React Refresh] Failed to set up the socket connection.

### ISSUE THREAD

**Issue by nkhi** [lxieyang/chrome-extension-boilerplate-react#211]
### Discussed in https://github.com/lxieyang/chrome-extension-boilerplate-react/discussions/193

<div type='discussions-op-text'>

<sup>Originally posted by **nasim67reja** November 13, 2023</sup>
![FireShot Capture 002 - Extensions - extensions](https://github.com/lxieyang/chrome-extension-boilerplate-react/assets/69707467/bd2ca117-f543-43a7-9d15-f27dd8d1269d)
After cloning ,installing and deploying the same code to chrome i am facing this  react refresh error. Please help me to solve this error. is there anything i am missing.?</div>

**Comment by Anonymous-Humanoid** [comment]
Duplicate of #156, but for anyone who stumbles upon this, here's the change to make in `webpack.config.js` as per [this comment](https://github.com/lxieyang/chrome-extension-boilerplate-react/issues/156#issuecomment-1451358491):

```patch
-IS_DEV_MODE && new ReactRefreshWebpackPlugin(),
+IS_DEV_MODE && new ReactRefreshWebpackPlugin({ overlay: false }),
```
