### ISSUE TITLE
Making it compatible with Firefox

### ISSUE THREAD

**Issue by BjoernRave** [lxieyang/chrome-extension-boilerplate-react#24]
It would be great if the extension would also work with firefox out of the box. For that [https://github.com/mozilla/web-ext](web-ext) could be used.
There is also a webpack plugin: 
https://github.com/ianwalter/web-ext-webpack-plugin
https://github.com/hiikezoe/web-ext-webpack-plugin

**Comment by YoucefHQ** [comment]
+1, would be amazing!

**Comment by lxieyang** [comment]
Please feel free to submit PRs that achieve this!

**Comment by lucasmrl** [comment]
@BjoernRave were you able to put together something?
