### ISSUE TITLE
Incorrect service worker spec in mv3

### ISSUE THREAD

**Issue by kashifshaikh** [lxieyang/chrome-extension-boilerplate-react#31]
Currently service workers in manifest.json is specified as an array. This doesn't work with chrome.

So we have to replace this:
` "background": [
    {
      "service_worker": [
        "background.bundle.js"
      ]
    }
  ],
`

What works is having a single service worker as per spec: https://developer.chrome.com/docs/extensions/mv3/manifest/
`"background": {
    "service_worker": "background.bundle.js"
  },`

**Comment by lxieyang** [comment]
Great catch! Thanks so much! It's fixed :-)
