### ISSUE TITLE
Please consider introducing react fast refresh

### ISSUE THREAD

**Issue by XuNeal** [lxieyang/chrome-extension-boilerplate-react#35]
This boilerplate is great. Thanks for the work.

Please consider introducing react fast refresh. React Fast Refresh will speed up the react development.

**Comment by johnAirRobe** [comment]
I second this. Would it be difficult to do this? I'm asking as I'd like to try and implement it myself.

**Comment by johnAirRobe** [comment]
@XuNeal and whoever else is interested. I was able to add React Fast Refresh. I followed the Prerequisites, Installation, and Usage sections of [the readme](https://github.com/pmmmwh/react-refresh-webpack-plugin).

Then I removed the use of `alias` from `webpack.config.js` and add `react-refresh/babel` to `.babelrc`. 

[Here's a gist](https://gist.github.com/johnAirRobe/3cd338435a7a14d002f60ef05dffeec6) of the changes I made.

When I ran the local server I got the following screen and was able to navigate to the newtab, options, panel, and popup pages.
![image](https://user-images.githubusercontent.com/95192755/162602144-3bbad33b-7bed-46e0-8daf-51968613f61d.png)

**Comment by devnomic** [comment]
Additional changes:
````
hot: true,
liveReload: false
````

`utils/webserver.js` to make it work.

**Comment by Godiswill** [comment]
I created a repo by create-react-app, so you can enjoy it. [cra-crx-boilerplate](https://github.com/Godiswill/cra-crx-boilerplate)

**Comment by lxieyang** [comment]
Done!
