### ISSUE TITLE
[suggestion] reference @types/chrome as a dependency

### ISSUE THREAD

**Issue by hudidit** [lxieyang/chrome-extension-boilerplate-react#4]
To have better intelligent code completion and type hint, I suggest to reference [@types/chrome](https://www.npmjs.com/package/@types/chrome) as a dependency. It also saves time from looking for function signatures in the docs.

建议把 [@types/chrome](https://www.npmjs.com/package/@types/chrome) 作为 dependency 引入，这样在 VS Code 里面能自动提示属性名、方法名和函数签名。写起来会快捷很多。

This is a very good boilerplate to start creating a new extension with. Great work!

**Comment by lxieyang** [comment]
Thanks! Will do!

**Comment by lxieyang** [comment]
also acknowledged your contribution! https://github.com/lxieyang/chrome-extension-boilerplate-react#intelligent-code-completion
thanks again!
