### ISSUE TITLE
Running background script continously

### ISSUE THREAD

**Issue by hassan-dev** [lxieyang/chrome-extension-boilerplate-react#41]
Service worker auto get into inactive mode and background script is not running in background at all. We can not use persistent in manifest 3.0, What is the work around on that. I am running setInterval callback in my background script, which only running when background page open, on close service worker auto get into inactive mode.

**Comment by hassan-dev** [comment]
@lxieyang @twigs67 help needed buddy

**Comment by frankgo81** [comment]
""Moving from timers to alarms "

Refer: https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/

**Comment by tungnnt** [comment]
I use this script at the top of my service worker code:
```
chrome.alarms.create({ delayInMinutes: 3 });

chrome.alarms.onAlarm.addListener(() => {
  chrome.action.setIcon({
    path: getRandomIconPath(),
  });
});
```
But the extension still goes to inactive service worker state after I restart chrome? Could you help me ~
