### ISSUE TITLE
JS source maps fail to load

### ISSUE THREAD

**Issue by danielcaldas** [lxieyang/chrome-extension-boilerplate-react#43]
![image](https://user-images.githubusercontent.com/11733994/116633979-75fe1200-a98d-11eb-8b11-0aaf30f994fc.png)

It might be a chrome bug. Just recently started seeing this in my webpack based setup. I'm looking around for other open-source extensions/boilerplates and it appears that all face the same issue?

Are you aware of this? Thanks!

**Comment by shunyun-bp** [comment]
Just figured this one out...  In webpack use 
`options.devtool = 'inline-cheap-module-source-map';`
Refer to [https://stackoverflow.com/questions/61462586/can-i-enable-sourcemaps-in-a-chrome-extension](https://stackoverflow.com/questions/61462586/can-i-enable-sourcemaps-in-a-chrome-extension)
