### ISSUE TITLE
Webpack failing to compile

### ISSUE THREAD

**Issue by owlyowl** [lxieyang/chrome-extension-boilerplate-react#44]
After a fresh install build and start webpack is failing to compile.

cacheable modules 1.34 MiB
  modules by path ./node_modules/ 1.3 MiB 47 modules
  modules by path ./src/ 36.9 KiB
    modules by path ./src/pages/ 33.5 KiB 30 modules
    modules by path ./src/assets/img/ 115 bytes
      ./src/assets/img/logo.svg 52 bytes [built] [code generated]
      ./src/assets/img/tmp-launcher128.png 63 bytes [built] [code generated]
    ./src/containers/Greetings/Greetings.jsx 3.28 KiB [built] [code generated]
./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]

ERROR in Unexpected string in JSON at position 355

webpack 5.23.0 compiled with 1 error in 10130 ms
i ｢wdm｣: Failed to compile.

**Comment by clasick** [comment]
@owlyowl I have the same issue. Were you able to fix this?
