### ISSUE TITLE
Publish to chrome store

### ISSUE THREAD

**Issue by hassan-dev** [lxieyang/chrome-extension-boilerplate-react#5]
Is there any issue while publish to chrome extension store the build folder?

**Comment by lxieyang** [comment]
Not that I know of? Are you experiencing any? If so, please let me know! Thanks!

**Comment by hassan-dev** [comment]
Did anyone ever submit their build to chrome store using this boilerplate?

**Comment by lxieyang** [comment]
Yes! As a matter of fact I have a Vertical Tabs chrome extension based on this boilerplate: https://github.com/lxieyang/vertical-tabs-chrome-extension

**Comment by hassan-dev** [comment]
@lxieyang  Great, please add Async Await support

**Comment by lxieyang** [comment]
Have you tried it out? I'm using async/await with no problems on my end. If you're having trouble, would you post in another issue about how to reproduce it so I can take a look? Thanks a lot!
