### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by hassan-dev** [lxieyang/chrome-extension-boilerplate-react#6]
Hey buddy, how about if we add structure like MVC or something to organize our code more better way, When our extension went bigger and bigger it always tough to maintain the code so any architecture would be best thing. :)

**Comment by lxieyang** [comment]
I think React by itself is already using MVC?

**Comment by hassan-dev** [comment]
> I think React by itself is already using MVC?

No its not using MVC at all, this would be great if we have more folders since our extension getting bigger and bigger

**Comment by lxieyang** [comment]
Hi, please feel free to create a new branch and submit a PR! As a boilerplate, I would like to keep things simple for now, and put more advanced features in different branches :-)
