### ISSUE TITLE
I cant run npm start

### ISSUE THREAD

**Issue by teffy-tr** [lxieyang/chrome-extension-boilerplate-react#64]
I'm having this error. What fix should be done?

![Screen Shot 2021-08-20 at 10 28 11 PM](https://user-images.githubusercontent.com/88047480/130248726-d4aca4a7-4549-45ba-9156-4ee5e7a655c7.png)

**Comment by hankxdev** [comment]
you might update the webpack-dev-server to 4.x, please use 3.x.
