### ISSUE TITLE
Does this solution supports Mac M1 Chip?

### ISSUE THREAD

**Issue by teffy-tr** [lxieyang/chrome-extension-boilerplate-react#65]
I'm encountering this issue that interfere the npm start. Is there any way to overcome this?
Thank you. 
![Screen Shot 2021-08-24 at 12 36 16 AM](https://user-images.githubusercontent.com/88047480/130484359-c1e1874c-d3b6-4e50-bd88-db3e827c3657.png)

**Comment by jonmiles** [comment]
The error clearly tells you that your webpack config is wrong!
