### ISSUE TITLE
SCSS/SASS?

### ISSUE THREAD

**Issue by dpw1** [lxieyang/chrome-extension-boilerplate-react#7]
First of all, I'd like to say that I'm genuinely amazed by this boilerplate. By far the best I've seen so far. Thank you very much for the efforts and the kindness to open source it.

Secondly, would it be possible to add support for SCSS and SASS? 

Thank you!

**Comment by hassan-dev** [comment]
@lxieyang Yes man, I am also very happy about this boilerplate, what an amazing boilerplate for React Lovers

**Comment by lxieyang** [comment]
Hi, I'm so glad that you love this! 

I suppose that can be arranged! I'm currently tied up with a deadline at work, but will get to it in early June!

**Comment by lxieyang** [comment]
sass/scss now supported @dpw1 @hassan-dev
