### ISSUE TITLE
static assets

### ISSUE THREAD

**Issue by Besuf** [lxieyang/chrome-extension-boilerplate-react#82]
Hey is there anyway I can point to the location of static assets like you use public folder inside any react app. I have many static  assets I wanna use in my project other that images, like json. What do you think the best way to go about this in this boilerplate

**Comment by lxieyang** [comment]
Would you try using the `chrome.runtime.getURL` API on static assets. see here: https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL
