### ISSUE TITLE
Several problems currently encountered （important ）

### ISSUE THREAD

**Issue by fariellany** [lxieyang/chrome-extension-boilerplate-react#83]
## problem

1. During hot loading, the previously packaged files will not be removed, resulting in a large package （so Oops）
2. When there is an error, no error will be prompted when npm run build is executed, and it can only be found through npm run start （so Oops）

## Suggest
1. Can the template be replaced with typescript and less or sass? 
2.  add git commit verification

**Comment by lxieyang** [comment]
problem:
1: should be fixed (#81)
2: I think it's customary for production versions to behave like this?

suggest:
1. It supports typescript already!
2. feel free to add it to your fork (prettier commit hooks, etc.)! I would like to keep this boilerplate as simple as possible.
