### ISSUE TITLE
Uncaught TypeError: self.location.reload is not a function

### ISSUE THREAD

**Issue by peter-palmer** [lxieyang/chrome-extension-boilerplate-react#84]
The error:
```
Uncaught TypeError: self.location.reload is not a function
    at Object.staticChanged [as static-changed] (background.bundle.js:2632)
    at background.bundle.js:3869
    at WebSocket.<anonymous> (background.bundle.js:2475)
```

I have just written some lines of code at Background/index.js and those errors appeared. How can I solve this?

I have seen too in the background.bundle.js this:
![image](https://user-images.githubusercontent.com/58218056/145635903-94a258db-1d31-4862-8e26-b247d4fa3332.png)

**Comment by leanderseige** [comment]
https://github.com/lxieyang/chrome-extension-boilerplate-react/issues/80

**Comment by lxieyang** [comment]
should be solved.
