### ISSUE TITLE
Not able to receive logs from React Popup

### ISSUE THREAD

**Issue by yannikw23** [lxieyang/chrome-extension-boilerplate-react#85]
Hi there, first of all: amazing boilerplate! It's working fantastic and has made the setup of our chrome extension sooo much easier - thanks a lot for your work!!

I've encountered an issue with logging anything from within `pages/Popup`. In there I'm using React and everything renders correctly and all logic is executed as expected. However, no logs from `Popup/index.tsx` are displayed in the browser console. Am I missing anything? 
Is there something in the webpack config which omits any `console.log` call in the build folder?

Any help would be much appreciated!

**Comment by leanderseige** [comment]
Right-click the extension icon and click "Inspect popup"?

**Comment by yannikw23** [comment]
Wow, haha! That was it. This is the first time I'm using the boilerplate. In the default extension setup, logs are directly printed to the browser's main console. 

Thanks a lot!

**Comment by leanderseige** [comment]
Great, can we close this issue now?
