### ISSUE TITLE
websocket connection error

### ISSUE THREAD

**Issue by qrk12** [lxieyang/chrome-extension-boilerplate-react#93]
![20220123190424](https://user-images.githubusercontent.com/20502951/150675486-2a80010d-1f13-40fb-b57b-0b1d0b6a2f67.jpg)

**Comment by GhazanfarKhan** [comment]
When you have attached this extension and you stop the npm start command this error will be shown, because extension files is serving from this local server. Create a build and refresh it will be gone.

**Comment by qrk12** [comment]
thank you
